{% set name = "hazardous" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hazardous-{{ version }}.tar.gz
  sha256: 4cb8fbe3e5a328ad012bd936b2345b53027ce4fb69162391d4a7af2473332199

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core
    - pip
    - numpy
    - scikit-learn
    - tqdm
    - lifelines
  run:
    - python >={{ python_min }}
    - numpy
    - scikit-learn
    - tqdm
    - lifelines
    - setuptools

test:
  imports:
    - hazardous
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/soda-inria/hazardous
  summary: Predictive Competing Risks and Survival Analysis.
  dev_url: https://github.com/soda-inria/hazardous
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Vincent-Maladiere
